/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DrawingDoom (https://sketchfab.com/kimgd247)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bmw-i8-3d-model-view-ace048670f564a318bd684fed0dffded
Title: BMW I8 3d model view
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/bmw_i8_3d_model_view.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="59db1407c5b6430e82317dcfab04caf6fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.001}
          >
            <group name="RootNode">
              <group
                name="Dummy006"
                position={[-101.9761, 101.8005, 11544.1738]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <group
                  name="Cylinder5426"
                  position={[142.6216, 226.0625, -47.2549]}
                  rotation={[-2.9799, 0, Math.PI]}
                >
                  <group
                    name="Object051"
                    position={[0, 0, 0.0004]}
                    rotation={[0.1411, Math.PI / 2, 0]}
                    scale={[4.2469, 4.2469, 9.3521]}
                  >
                    <group
                      name="Object_6"
                      position={[-0.0001, -0.0001, -0.2155]}
                    >
                      <mesh
                        name="Object051_Material_#327_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Object051_Material_#327_0"].geometry}
                        material={materials.Material_327}
                      />
                      <mesh
                        name="Object051_Material_#326_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Object051_Material_#326_0"].geometry}
                        material={materials.Material_326}
                      />
                      <mesh
                        name="Object051_Material_#239_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Object051_Material_#239_0"].geometry}
                        material={materials.Material_239}
                      />
                      <mesh
                        name="Object051_Material_#34_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Object051_Material_#34_0"].geometry}
                        material={materials.Material_34}
                      />
                      <mesh
                        name="Object051_Material_#237_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Object051_Material_#237_0"].geometry}
                        material={materials.Material_237}
                      />
                    </group>
                    <group
                      name="Cylinder044"
                      position={[0.0228, 0.0642, 0.0863]}
                      rotation={[0, 0, -0.0033]}
                      scale={[0.969, 0.969, 1]}
                    >
                      <group
                        name="Object_13"
                        position={[-0.0235, -0.0664, -0.3018]}
                      >
                        <mesh
                          name="Cylinder044_Material_#4632_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes["Cylinder044_Material_#4632_0"].geometry
                          }
                          material={materials.Material_4632}
                        />
                      </group>
                    </group>
                  </group>
                </group>
                <group
                  name="Cylinder5429"
                  position={[-142.6261, 226.0469, -47.2551]}
                  rotation={[0.1617, 0, Math.PI]}
                  scale={[-1, 1, 1]}
                >
                  <group
                    name="Object049"
                    position={[0, 0, 0.0004]}
                    rotation={[-2.3694, Math.PI / 2, 0]}
                    scale={[4.2469, 4.2469, 9.3521]}
                  >
                    <group name="Object_17" position={[0.0002, 0, -0.2155]}>
                      <mesh
                        name="Object049_Material_#327_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Object049_Material_#327_0"].geometry}
                        material={materials.Material_327}
                      />
                      <mesh
                        name="Object049_Material_#326_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Object049_Material_#326_0"].geometry}
                        material={materials.Material_326}
                      />
                      <mesh
                        name="Object049_Material_#239_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Object049_Material_#239_0"].geometry}
                        material={materials.Material_239}
                      />
                      <mesh
                        name="Object049_Material_#34_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Object049_Material_#34_0"].geometry}
                        material={materials.Material_34}
                      />
                      <mesh
                        name="Object049_Material_#237_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Object049_Material_#237_0"].geometry}
                        material={materials.Material_237}
                      />
                    </group>
                    <group
                      name="Cylinder043"
                      position={[0.0231, 0.0642, 0.0863]}
                      rotation={[0, 0, -0.0033]}
                      scale={[0.969, 0.969, 1]}
                    >
                      <group
                        name="Object_24"
                        position={[-0.0238, -0.0664, -0.3018]}
                      >
                        <mesh
                          name="Cylinder043_Material_#463_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes["Cylinder043_Material_#463_0"].geometry
                          }
                          material={materials.Material_463}
                        />
                      </group>
                    </group>
                  </group>
                </group>
                <group
                  name="Cylinder5430"
                  position={[109.4849, -215.0781, -44.6884]}
                  rotation={[-0.6141, 0, -Math.PI]}
                  scale={[1, 2.0444, 2.0444]}
                >
                  <group
                    name="Cylinder5425"
                    position={[-33.1366, -1.3364, -0.6123]}
                    rotation={[2.9799, 0, 0]}
                    scale={[1, 0.4891, 0.4891]}
                  >
                    <group
                      name="Object1892"
                      position={[18.1654, -0.001, -0.0005]}
                      rotation={[0.6514, 1.5708, 0]}
                      scale={[4.2469, 4.2469, 9.3521]}
                    >
                      <group name="Object_29" position={[-0.0003, 0, -1.5512]}>
                        <mesh
                          name="Object1892_Material_#327_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes["Object1892_Material_#327_0"].geometry
                          }
                          material={materials.Material_327}
                        />
                        <mesh
                          name="Object1892_Material_#326_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes["Object1892_Material_#326_0"].geometry
                          }
                          material={materials.Material_326}
                        />
                        <mesh
                          name="Object1892_Material_#34_0"
                          castShadow
                          receiveShadow
                          geometry={nodes["Object1892_Material_#34_0"].geometry}
                          material={materials.Material_34}
                        />
                        <mesh
                          name="Object1892_Material_#239_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes["Object1892_Material_#239_0"].geometry
                          }
                          material={materials.Material_239}
                        />
                        <mesh
                          name="Object1892_Material_#237_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes["Object1892_Material_#237_0"].geometry
                          }
                          material={materials.Material_237}
                        />
                      </group>
                      <group
                        name="Cylinder5424"
                        position={[0, -0.002, 0]}
                        rotation={[0, 0, -0.0033]}
                        scale={[0.969, 0.969, 1]}
                      >
                        <group
                          name="Object_36"
                          position={[-0.0003, 0, -1.5512]}
                        >
                          <mesh
                            name="Cylinder5424_Material_#4632_0"
                            castShadow
                            receiveShadow
                            geometry={
                              nodes["Cylinder5424_Material_#4632_0"].geometry
                            }
                            material={materials.Material_4632}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group
                  name="Cylinder5431"
                  position={[-109.485, -215.0781, -44.6884]}
                  rotation={[2.5275, 0, Math.PI]}
                  scale={[-1, 2.0444, 2.0444]}
                >
                  <group
                    name="Cylinder5428"
                    position={[-33.1412, 1.3374, 0.6145]}
                    rotation={[2.9799, 0, 0]}
                    scale={[1, 0.4891, 0.4891]}
                  >
                    <group
                      name="Object043"
                      position={[18.1701, -0.0039, -0.0005]}
                      rotation={[-1.8658, Math.PI / 2, 0]}
                      scale={[4.2469, 4.2469, 9.3521]}
                    >
                      <group name="Object_41" position={[-0.0003, 0, -1.5512]}>
                        <mesh
                          name="Object043_Material_#327_0"
                          castShadow
                          receiveShadow
                          geometry={nodes["Object043_Material_#327_0"].geometry}
                          material={materials.Material_327}
                        />
                        <mesh
                          name="Object043_Material_#326_0"
                          castShadow
                          receiveShadow
                          geometry={nodes["Object043_Material_#326_0"].geometry}
                          material={materials.Material_326}
                        />
                        <mesh
                          name="Object043_Material_#34_0"
                          castShadow
                          receiveShadow
                          geometry={nodes["Object043_Material_#34_0"].geometry}
                          material={materials.Material_34}
                        />
                        <mesh
                          name="Object043_Material_#239_0"
                          castShadow
                          receiveShadow
                          geometry={nodes["Object043_Material_#239_0"].geometry}
                          material={materials.Material_239}
                        />
                        <mesh
                          name="Object043_Material_#237_0"
                          castShadow
                          receiveShadow
                          geometry={nodes["Object043_Material_#237_0"].geometry}
                          material={materials.Material_237}
                        />
                      </group>
                      <group
                        name="Cylinder031"
                        rotation={[0, 0, -0.0033]}
                        scale={[0.969, 0.969, 1]}
                      >
                        <group
                          name="Object_48"
                          position={[-0.0003, 0, -1.5512]}
                        >
                          <mesh
                            name="Cylinder031_Material_#463_0"
                            castShadow
                            receiveShadow
                            geometry={
                              nodes["Cylinder031_Material_#463_0"].geometry
                            }
                            material={materials.Material_463}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group
                  name="Plane007"
                  position={[0, 0.0029, 0]}
                  rotation={[-Math.PI / 2, 0, Math.PI]}
                  scale={4.1153}
                >
                  <group
                    name="Object_51"
                    position={[11.4457, 3.0057, -70.9926]}
                  >
                    <mesh
                      name="Plane007_08_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane007_08_-_Default_0"].geometry}
                      material={materials["08_-_Default"]}
                    />
                    <mesh
                      name="Plane007_Material_#34_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane007_Material_#34_0"].geometry}
                      material={materials.Material_34_0}
                    />
                    <mesh
                      name="Plane007_Material_#34_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane007_Material_#34_0_1"].geometry}
                      material={materials.Material_34_1}
                    />
                    <mesh
                      name="Plane007_Material_#34_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane007_Material_#34_0_2"].geometry}
                      material={materials.Material_34}
                    />
                  </group>
                </group>
                <group
                  name="Plane010"
                  position={[0, 0.0029, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={4.1153}
                >
                  <group
                    name="Object_57"
                    position={[-16.3509, -5.0725, 81.4579]}
                  >
                    <mesh
                      name="Plane010_Material_#32_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane010_Material_#32_0"].geometry}
                      material={materials.Material_32}
                    />
                  </group>
                </group>
                <group
                  name="Plane011"
                  position={[0, 0.0029, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={4.1153}
                >
                  <group
                    name="Object_60"
                    position={[-8.3911, 11.9219, 45.0988]}
                  >
                    <mesh
                      name="Plane011_Material_#464_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane011_Material_#464_0"].geometry}
                      material={materials.Material_464}
                    />
                  </group>
                </group>
                <group
                  name="Object002"
                  position={[0, 0.0029, 0]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  scale={4.1153}
                >
                  <group name="Object_63" position={[-7.528, 6.1879, 31.849]}>
                    <mesh
                      name="Object002_Material_#33_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Object002_Material_#33_0"].geometry}
                      material={materials.Material_33}
                    />
                  </group>
                </group>
                <group
                  name="Object003"
                  position={[0, -303.8428, -4.4306]}
                  rotation={[0.0719, 0, Math.PI / 2]}
                  scale={4.1153}
                >
                  <group
                    name="Object_66"
                    position={[-2.9839, -3.1298, -0.2617]}
                  >
                    <mesh
                      name="Object003_08_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Object003_08_-_Default_0"].geometry}
                      material={materials["08_-_Default"]}
                    />
                  </group>
                </group>
                <group
                  name="Plane016"
                  position={[14.0498, -226.9316, 2.9665]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={[2.7111, 3.9619, 3.4763]}
                >
                  <mesh
                    name="Plane016_Material_#34_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Plane016_Material_#34_0"].geometry}
                    material={materials.Material_34_2}
                  />
                </group>
                <group
                  name="Object014"
                  position={[0, -290.8994, -5.689]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={[1.7639, 3.4447, 4.1153]}
                >
                  <group
                    name="Object_71"
                    position={[-3.2633, 2.7552, -11.7002]}
                  >
                    <mesh
                      name="Object014_Material_#34_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Object014_Material_#34_0"].geometry}
                      material={materials.Material_34_2}
                    />
                  </group>
                </group>
                <group
                  name="Plane017"
                  position={[0, -191.8037, 25.3012]}
                  rotation={[-0.0873, 0, Math.PI / 2]}
                  scale={4.1153}
                >
                  <group name="Object_74" position={[8.9002, 24.1834, 3.0066]}>
                    <mesh
                      name="Plane017_Material_#236_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane017_Material_#236_0"].geometry}
                      material={materials.Material_236}
                    />
                  </group>
                </group>
                <group
                  name="Plane018"
                  position={[0, 0.0029, 2.4107]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={4.1153}
                >
                  <group
                    name="Object_77"
                    position={[-35.6709, 26.1806, -9.3316]}
                  >
                    <mesh
                      name="Plane018_Material_#236_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane018_Material_#236_0"].geometry}
                      material={materials.Material_236}
                    />
                  </group>
                </group>
                <group
                  name="Plane019"
                  position={[0, -272.7207, -12.108]}
                  rotation={[0.1614, 0, Math.PI / 2]}
                  scale={[4.1153, 4.1153, 4.1154]}
                >
                  <group name="Object_80" position={[1.1359, 3.3237, -0.7746]}>
                    <mesh
                      name="Plane019_Material_#34_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane019_Material_#34_0"].geometry}
                      material={materials.Material_34_2}
                    />
                  </group>
                </group>
                <group
                  name="Plane020"
                  position={[0, 0.0029, 0]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  scale={4.1153}
                >
                  <group name="Object_83" position={[13.5863, 6.6424, 31.0825]}>
                    <mesh
                      name="Plane020_08_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane020_08_-_Default_0"].geometry}
                      material={materials["08_-_Default"]}
                    />
                  </group>
                </group>
                <group
                  name="Plane021"
                  position={[0, 0.0029, 0]}
                  rotation={[-Math.PI / 2, 0, Math.PI]}
                  scale={4.1153}
                >
                  <group name="Object_86" position={[18.0436, 6.9515, 73.3691]}>
                    <mesh
                      name="Plane021__0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Plane021__0.geometry}
                      material={materials.Plane021__0}
                    />
                  </group>
                </group>
                <group
                  name="Plane022"
                  position={[0, 0.0029, 0]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  scale={4.1153}
                >
                  <group
                    name="Object_89"
                    position={[33.9152, -15.7802, 33.6647]}
                  >
                    <mesh
                      name="Plane022_Material_#34_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane022_Material_#34_0"].geometry}
                      material={materials.Material_34_0}
                    />
                  </group>
                </group>
                <group
                  name="Plane023"
                  position={[0, -40.4531, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={4.1153}
                >
                  <group
                    name="Object_92"
                    position={[-30.3851, 16.5905, -5.0579]}
                  >
                    <mesh
                      name="Plane023_Material_#239_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane023_Material_#239_0"].geometry}
                      material={materials.Material_239}
                    />
                    <mesh
                      name="Plane023_Material_#273_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane023_Material_#273_0"].geometry}
                      material={materials.Material_273}
                    />
                    <mesh
                      name="Plane023_Material_#285_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane023_Material_#285_0"].geometry}
                      material={materials.Material_285}
                    />
                  </group>
                </group>
                <group
                  name="Plane040"
                  position={[0.2412, -333.2949, -28.9699]}
                  rotation={[Math.PI / 2, -0.3178, 0]}
                  scale={[-5.4457, 3.6934, 4.1154]}
                >
                  <group name="Object_97" position={[10.5964, 1.1185, 4.4396]}>
                    <mesh
                      name="Plane040_Material_#32_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane040_Material_#32_0"].geometry}
                      material={materials.Material_32}
                    />
                  </group>
                </group>
                <group
                  name="Plane041"
                  position={[0, -312.1953, -16.5767]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={4.1153}
                >
                  <group name="Object_100" position={[-21.4346, -1.1075, 0]}>
                    <mesh
                      name="Plane041__0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Plane041__0.geometry}
                      material={materials.Plane021__0}
                    />
                  </group>
                </group>
                <group
                  name="Object016"
                  position={[0, -304.4746, -16.5767]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={4.1153}
                >
                  <group name="Object_103" position={[-21.4346, -1.1075, 0]}>
                    <mesh
                      name="Object016_Material_#330_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Object016_Material_#330_0"].geometry}
                      material={materials.Material_330}
                    />
                  </group>
                </group>
                <group
                  name="Plane045"
                  position={[0, 0.0029, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={4.1153}
                >
                  <group
                    name="Object_106"
                    position={[-0.2448, -7.2552, 85.2527]}
                  >
                    <mesh
                      name="Plane045_08_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane045_08_-_Default_0"].geometry}
                      material={materials["08_-_Default"]}
                    />
                  </group>
                </group>
                <group
                  name="Plane046"
                  position={[0, -352.5342, -54.4385]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={4.1153}
                >
                  <mesh
                    name="Plane046_Material_#324_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Plane046_Material_#324_0"].geometry}
                    material={materials.Material_324}
                  />
                  <mesh
                    name="Plane046_Material_#34_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Plane046_Material_#34_0"].geometry}
                    material={materials.Material_34_2}
                  />
                </group>
                <group
                  name="Cylinder001"
                  position={[42.5361, -204.0664, 11.3211]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={[4.1153, 4.1153, 2.6188]}
                >
                  <mesh
                    name="Cylinder001_Material_#34_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Cylinder001_Material_#34_0"].geometry}
                    material={materials.Material_34}
                  />
                </group>
                <group
                  name="Cylinder002"
                  position={[42.5361, -204.0664, 12.0741]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={[3.6873, 3.6873, 0.7791]}
                >
                  <mesh
                    name="Cylinder002_Material_#34_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Cylinder002_Material_#34_0"].geometry}
                    material={materials.Material_34}
                  />
                </group>
                <group
                  name="Box011"
                  position={[22.0878, -208.8398, -8.8363]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={[4.1153, 4.1153, 2.2736]}
                >
                  <mesh
                    name="Box011_Material_#34_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Box011_Material_#34_0"].geometry}
                    material={materials.Material_34_2}
                  />
                </group>
                <group
                  name="Box012"
                  position={[0, 343.4736, -23.3927]}
                  rotation={[-Math.PI / 2, 0, Math.PI]}
                  scale={4.1153}
                >
                  <mesh
                    name="Box012_Material_#34_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Box012_Material_#34_0"].geometry}
                    material={materials.Material_34_2}
                  />
                  <mesh
                    name="Box012_Material_#324_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Box012_Material_#324_0"].geometry}
                    material={materials.Material_324}
                  />
                </group>
                <group
                  name="Plane047"
                  position={[-0.0001, -354.1182, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={4.1153}
                >
                  <group
                    name="Object_121"
                    position={[-19.1944, -12.815, -5.0579]}
                  >
                    <mesh
                      name="Plane047_Material_#33_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane047_Material_#33_0"].geometry}
                      material={materials.Material_33}
                    />
                  </group>
                </group>
                <group
                  name="Plane048"
                  position={[0, 0.0029, 0]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={4.1153}
                >
                  <group name="Object_124" position={[-62.528, 2.5705, 4.1963]}>
                    <mesh
                      name="Plane048_Material_#464_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane048_Material_#464_0"].geometry}
                      material={materials.Material_464}
                    />
                  </group>
                </group>
                <group
                  name="Plane049"
                  position={[0, 0.0029, 0]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  scale={4.1153}
                >
                  <group
                    name="Object_127"
                    position={[7.2851, -1.8662, 31.9672]}
                  >
                    <mesh
                      name="Plane049_08_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane049_08_-_Default_0"].geometry}
                      material={materials["08_-_Default"]}
                    />
                  </group>
                </group>
                <group
                  name="Object017"
                  position={[0, 0.0029, 0]}
                  rotation={[-Math.PI / 2, 0, Math.PI]}
                  scale={4.1153}
                >
                  <group
                    name="Object_130"
                    position={[18.0436, 6.9515, 73.3691]}
                  >
                    <mesh
                      name="Object017_08_-_Default3_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Object017_08_-_Default3_0"].geometry}
                      material={materials["08_-_Default3"]}
                    />
                  </group>
                </group>
                <group
                  name="Box013"
                  position={[0, 0.0029, 0]}
                  rotation={[-0.1745, 0, -Math.PI]}
                  scale={[4.1153, 4.1153, 21.6838]}
                >
                  <group name="Object_133" position={[1.5621, -38.047, 4.9925]}>
                    <mesh
                      name="Box013_19_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Box013_19_-_Default_0"].geometry}
                      material={materials["19_-_Default"]}
                    />
                  </group>
                </group>
                <group
                  name="Cylinder003"
                  position={[0, 179.2217, 80.2833]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  scale={4.1153}
                >
                  <group name="Object_136" position={[-0.0041, 0, -1.163]}>
                    <mesh
                      name="Cylinder003_19_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Cylinder003_19_-_Default_0"].geometry}
                      material={materials["19_-_Default"]}
                    />
                  </group>
                </group>
                <group
                  name="Object018"
                  position={[0, 174.7227, 80.7301]}
                  rotation={[-0.1745, 0, -Math.PI]}
                  scale={[15.7662, 3.44, 18.1253]}
                >
                  <group name="Object_139" position={[0, 0.2137, -0.0825]}>
                    <mesh
                      name="Object018__0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object018__0.geometry}
                      material={materials.Plane021__0}
                    />
                  </group>
                </group>
                <group
                  name="Object019"
                  position={[0, 174.7227, 80.7301]}
                  rotation={[-0.1745, 0, -Math.PI]}
                  scale={[15.7662, 3.44, 18.1253]}
                >
                  <group name="Object_142" position={[0, 0.2137, -0.0825]}>
                    <mesh
                      name="Object019_08_-_Default3_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Object019_08_-_Default3_0"].geometry}
                      material={materials["08_-_Default3"]}
                    />
                  </group>
                </group>
                <group
                  name="Object020"
                  position={[0, 0.0029, 0]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  scale={4.1153}
                >
                  <group name="Object_145" position={[-7.528, 6.1879, 31.849]}>
                    <mesh
                      name="Object020_Material_#464_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Object020_Material_#464_0"].geometry}
                      material={materials.Material_464}
                    />
                  </group>
                </group>
                <group
                  name="Plane050"
                  position={[0, 0.0029, 0]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={4.1153}
                >
                  <group name="Object_148" position={[8.9824, 4.4505, 20.5388]}>
                    <mesh
                      name="Plane050_20_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane050_20_-_Default_0"].geometry}
                      material={materials["20_-_Default"]}
                    />
                  </group>
                </group>
                <group
                  name="Cylinder004"
                  position={[0.1279, 343.0303, 20.3831]}
                  rotation={[-Math.PI / 2, 0, Math.PI]}
                  scale={4.1153}
                >
                  <mesh
                    name="Cylinder004_Material_#34_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Cylinder004_Material_#34_0"].geometry}
                    material={materials.Material_34_1}
                  />
                </group>
                <group
                  name="Cylinder005"
                  position={[0.1279, 344.1494, 20.3831]}
                  rotation={[-Math.PI / 2, 0, Math.PI]}
                  scale={[5.665, 5.665, 1.7818]}
                >
                  <mesh
                    name="Cylinder005_Material_#239_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Cylinder005_Material_#239_0"].geometry}
                    material={materials.Material_239}
                  />
                </group>
                <group
                  name="Cylinder006"
                  position={[0.1279, 344.1494, 20.3831]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[7.5683, 7.5683, 4.1153]}
                >
                  <mesh
                    name="Cylinder006_Material_#237_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Cylinder006_Material_#237_0"].geometry}
                    material={materials.Material_237}
                  />
                </group>
                <group
                  name="Cylinder007"
                  position={[0.1289, -346.7314, -13.9799]}
                  rotation={[0.5248, 0, Math.PI / 2]}
                  scale={[7.5683, 7.5683, 4.1153]}
                >
                  <mesh
                    name="Cylinder007_Material_#237_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Cylinder007_Material_#237_0"].geometry}
                    material={materials.Material_237}
                  />
                </group>
                <group
                  name="Cylinder008"
                  position={[0.1289, -346.7314, -13.9799]}
                  rotation={[0.5248, 0, 0]}
                  scale={[5.665, 5.665, 1.7818]}
                >
                  <mesh
                    name="Cylinder008_Material_#239_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Cylinder008_Material_#239_0"].geometry}
                    material={materials.Material_239}
                  />
                </group>
                <group
                  name="Object029"
                  position={[0, 0.0029, 0]}
                  rotation={[-Math.PI / 2, 0, Math.PI]}
                  scale={4.1153}
                >
                  <group
                    name="Object_161"
                    position={[11.4457, 3.0057, -70.9926]}
                  >
                    <mesh
                      name="Object029_Material_#34_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Object029_Material_#34_0"].geometry}
                      material={materials.Material_34_0}
                    />
                    <mesh
                      name="Object029_08_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Object029_08_-_Default_0"].geometry}
                      material={materials["08_-_Default"]}
                    />
                  </group>
                </group>
                <group
                  name="Torus007"
                  position={[-109.4903, -200.6045, 25.4648]}
                  rotation={[0.0687, 0.1184, 2.6139]}
                  scale={[5.2403, 5.2714, 4.1549]}
                >
                  <group name="Object_165" position={[0.5393, 0, 0]}>
                    <mesh
                      name="Torus007_Material_#325_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Torus007_Material_#325_0"].geometry}
                      material={materials.Material_325}
                    />
                  </group>
                </group>
                <group
                  name="Object036"
                  position={[0, 0.0029, 0]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  scale={4.1153}
                >
                  <group
                    name="Object_168"
                    position={[-29.1174, -8.1519, 34.7631]}
                  >
                    <mesh
                      name="Object036_17_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Object036_17_-_Default_0"].geometry}
                      material={materials["17_-_Default"]}
                    />
                  </group>
                </group>
                <group
                  name="Object037"
                  position={[0, 0.0029, 0]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  scale={[4.3311, 4.3311, 4.1153]}
                >
                  <group
                    name="Object_171"
                    position={[75.9651, -6.4561, 31.2354]}
                  >
                    <mesh
                      name="Object037_17_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Object037_17_-_Default_0"].geometry}
                      material={materials["17_-_Default"]}
                    />
                  </group>
                </group>
                <group
                  name="Shape001"
                  position={[0, 0.0029, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={4.1153}
                >
                  <group
                    name="Object_174"
                    position={[-16.3509, -5.0725, 81.4579]}
                  >
                    <mesh
                      name="Shape001__0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Shape001__0.geometry}
                      material={materials.Plane021__0}
                    />
                  </group>
                </group>
                <group
                  name="Plane071"
                  position={[0, 0.0029, 7.0626]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  scale={[4.1153, 3.1958, 4.1153]}
                >
                  <group
                    name="Object_177"
                    position={[-33.7264, 8.4535, 29.8286]}
                  >
                    <mesh
                      name="Plane071_Material_#34_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane071_Material_#34_0"].geometry}
                      material={materials.Material_34_2}
                    />
                  </group>
                </group>
                <group
                  name="Plane072"
                  position={[0, 0.0029, 0]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  scale={4.1153}
                >
                  <group
                    name="Object_180"
                    position={[-20.239, 3.3227, 28.6947]}
                  >
                    <mesh
                      name="Plane072_08_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Plane072_08_-_Default_0"].geometry}
                      material={materials["08_-_Default"]}
                    />
                  </group>
                </group>
                <group
                  name="Plane073"
                  position={[0, 22.9883, -70.5164]}
                  rotation={[-Math.PI, 0, Math.PI / 2]}
                  scale={[-4.1153, 4.1153, 4.1153]}
                >
                  <mesh
                    name="Plane073_Material_#465_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Plane073_Material_#465_0"].geometry}
                    material={materials.Material_465}
                  />
                </group>
                <group
                  name="Object015"
                  position={[0, 0.0029, 0]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  scale={4.1153}
                >
                  <group name="Object_185" position={[-7.528, 6.1879, 31.849]}>
                    <mesh
                      name="Object015_Material_#33_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Object015_Material_#33_0"].geometry}
                      material={materials.Material_33}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/bmw_i8_3d_model_view.glb");
